version: "3.4"

services:
  weekgame-web:
    image: "weekgame"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - "NODE_ENV=production"
    depends_on:
      - weekgame-mongodb
    restart: always

  weekgame-mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
